<label for="institute">Institute : </label> 
    <span class="fw-bold">{{$academic->institute}}</span><br/>
<label for="edu_stage">Stage : </label> 
    <span class="fw-bold">{{$academic->edu_stage}}</span><br/>
<label for="edu_field">Study Field : </label> 
    <span class="fw-bold">{{$academic->edu_field}}</span><br/>
<label for="start_date">Start Date : </label> 
    <span class="fw-bold">{{$academic->start_date}}</span><br/>
<label for="end_date">End Date : </label> 
    <span class="fw-bold">{{$academic->end_date}}</span><br/>
